version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: care-for-me
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: CareForMe-Run55505=kksdf
      MYSQL_DATABASE: Care_For_Me
      MYSQL_USER: user_care-for-me
      MYSQL_PASSWORD: CareForMe2026Runggj
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql